AWSTemplateFormatVersion: "2010-09-09"
Description: Yet Analytics GitHub OIDC Identity Provider setup. This template is provided for documentation purposes only. You do not need to run it to run rds-db-init.

Parameters:
  ThumbprintList:
    Type: CommaDelimitedList
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1

Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    DeletionPolicy: Retain
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList: !Ref ThumbprintList

Outputs:
  OIDCProviderArn:
    Description: ARN of AWS IAM entry for GitHub OIDC Provider
    Value: !Ref GithubOidc
    Export:
      Name: !Sub "${AWS::StackName}:OIDCProviderArn"
